<script lang="ts">
	import MailingListCta from '$lib/mailing-list-cta.svelte';
	import MfaSeedInitializationDemo from './mfa-seed-initialization-demo.svelte';
	import { initializeSecret, secret } from './store';
	import SecretDisplayEditor from './secret-display-editor.svelte';
	import SecretUint8Display from './secret-uint8-display.svelte';
	import SecretBinDisplay from './secret-bin-display.svelte';
	import SecretCombinedDisplay from './secret-combined-display.svelte';
	import Authenticator from './authenticator.svelte';
	import Button from '$lib/button.svelte';
	import { onMount } from 'svelte';
	import Portal from './portal.svelte';
	import WindowVisualizer from './window-visualizer.svelte';

	onMount(() => {
		initializeSecret(secret.set);
	});

	let showAuthenticator = false;
	let mfaInitComplete = false;
</script>

<svelte:head>
	<title>How does MFA work? | Jackson Welsh</title>
	<meta property="og:type" content="article" />
	<meta property="og:title" content="How does MFA work?" />
	<meta property="og:url" content="https://jacksonwel.sh/blog/2024-01-31/how-does-mfa-work" />
	<meta property="og:site_name" content="Jackson Welsh" />
	<meta
		property="og:description"
		content="Lessons learned from building serverless applications on AWS."
	/>
	<meta property="og:article:published_time" content="2024-01-31" />
	<meta property="og:article:author" content="Jackson Welsh" />
	<meta property="og:article:tag" content="serverless" />
	<meta property="og:article:tag" content="cloud" />
	<meta property="og:article:tag" content="infrastructure" />
	<meta property="og:article:tag" content="devops" />
	<meta property="og:article:tag" content="aws" />
</svelte:head>

<div class="container mx-auto">
	<div class="text-left mt-3 text-slate-400 print:hidden flex">
		<a href="/" class="text-blue-400 hover:underline">~</a>
		/
		<a href="/blog" class="text-blue-400 hover:underline">blog</a>
		/how-does-mfa-work
	</div>
</div>

<Authenticator bind:show={showAuthenticator} />

<main class="mx-auto my-16 p-2 md:p-0">
	<article class="mx-auto prose dark:prose-invert">
		<div
			class="flex items-center flex-wrap rounded-md border-2 bg-gradient-to-tr dark:border-green-600 border-green-400 dark:from-blue-900/25 dark:to-green-900/25 from-blue-100 to-green-100 text-green-800 dark:text-green-200 p-4 my-4"
		>
			<div class="text-sm w-full">
				<strong>You found an unreleased blog post!</strong> All content here is tentative, and the final
				blog may look significantly different from what you see today. Shoot me an email if you have
				any comments.
			</div>
		</div>

		<h1 class="font-mono mb-2">How does MFA work?</h1>
		<div class="text-lg text-gray-600 dark:text-gray-400">SMS, TOTP, WebAuthn, oh my!</div>
		<time class="text-sm text-gray-600 dark:text-gray-400" datetime="2024-01-31">31 Jan 2024</time>

		<p>
			Passwords aren't enough to keep your most important accounts secure. As I <a
				href="../2024-01-24/passwords-suck">discussed last week,</a
			> there are many issues with using passwords to prove someone's identity. Multi-factor authentication
			(MFA) is one of the many tools that developers have to protect users' accounts from compromise.
		</p>

		<p>
			MFA comes in many forms–and not all forms of MFA are created equal. Let's take a look at your
			usual suspects:
		</p>

		<h3>SMS</h3>

		<p>
			SMS is probably the most ubiquitous, while also being the most flawed MFA solution. The
			application server generates a code (usually 6 digits) and sends a text to your registered
			phone number. The user enters the code (maybe with the help of their operating system[link to
			apple/google]), the site checks it against the code they generated, and the user is
			authenticated.
		</p>

		<p>[things about how sms sucks here]</p>

		<h3 class="drop-shadow-glow">Email</h3>

		<p>[details about email]</p>

		<h3>Time-based One Time Password (TOTP)</h3>

		<p>
			TOTP builds on the solutions introduced above by using an open algorithm to generate codes for
			you. Rather than receiving an email with a code for your account, you get a "seed" when
			setting up MFA. This seed, when input into any TOTP app, will generate 6-digit codes based on
			what time it is.
		</p>

		<p>
			TOTP has many advantages: it works entirely offline (your authenticator could be a device
			without internet access entirely), doesn't rely on vulnerable infrastructure, and is portable.
			If you change your phone number or email address, you can't receive MFA codes anymore. If you
			get a new phone or choose to use a new MFA app, you can simply export the seeds for your
			accounts[0] and load them into your new app.
		</p>

		<p>Let's take a closer look at how MFA works.</p>

		<p>
			It all starts with a secret. This is a random value generated by the server. I generated one
			for you in the browser and have saved it in LocalStorage:
		</p>

		<Portal label="base32" class="cursor-cell">
			<SecretDisplayEditor />
		</Portal>

		<p>
			Hmm... that's not what my server sees. These random values are actually usually generated as
			sequences of integers:
		</p>

		<Portal label="uint8" class="cursor-cell">
			<SecretUint8Display />
		</Portal>

		<p>
			Unfortunately, converting these numbers to base32 is more involved than converting to hex. A
			base32 character represents 5 bits of data, while each number is an unsigned 8-bit integer.
			Let's convert these integers to binary to see what they represent in base32:
		</p>
		<Portal class="!block cursor-cell" label="uint8 binary">
			<SecretBinDisplay />
		</Portal>

		<p>
			Close, but not quite useful yet. 8-bit chunks are useful when working with ints, but less so
			when working with base32. Since each character in base32 represents a 5-bit chunk, let's
			switch from 8-bit to 5-bit.
		</p>
		<Portal class="!block cursor-cell" label="base32/binary">
			<SecretCombinedDisplay />
		</Portal>

		<p>
			There aren't many rules about how long or short the secret is, but after sampling a few of my
			MFA-protected accounts, I've seen anything from 10-20 bytes, resulting in 16-32 character
			base32 strings.
		</p>

		<p>
			Now that we have a secret, you can add it to an authenticator app. The QR code includes the
			secret, along with other metadata about the MFA codes.
		</p>

		<p>
			I suppose you'll need an authenticator to test this out. You can use an app you already have
			(Google Authenticator, Authy, etc.), or use the one I built for this page:
		</p>

		<div class="my-6 flex items-center justify-center">
			<Button on:click={() => (showAuthenticator = !showAuthenticator)}
				>{showAuthenticator ? 'Hide' : 'Show'} authenticator</Button
			>
		</div>

		<!-- <div
			class="relative p-4 rounded-md border-2 dark:border-gray-700 border-gray-300 mb-2 text-xs sm:text-sm md:text-base"
		>
			<div class="">
				<span class="dark:text-red-200">otpauth://totp/</span><span class="dark:text-orange-200"
					>JacksonWelsh</span
				><span class="">:</span><span class="dark:text-yellow-200">user@example.com</span><span
					class="">?secret=</span
				><span class="dark:text-green-200">{$secret}</span><span class="">&issuer=</span><span
					class="dark:text-blue-200">JacksonWelsh</span
				><span class="">&algorithm=</span><span class="dark:text-indigo-200">SHA-1</span><span
					class="">&digits=</span
				><span class="dark:text-purple-200">6</span><span class="">&period=</span><span
					class="text-pink-200">30</span
				>
			</div>
		</div> -->

		<Portal label="interactive">
			<MfaSeedInitializationDemo bind:mfaInitComplete />
		</Portal>

		<p>
			The registration process really doesn't involve much more than generate the secret described
			above, at least for the server. The reason you have to enter a code from your authenticator is
			to prove that your authenticator is set up correctly - nothing more.
		</p>

		<p>
			You may have noticed that you can sometimes use codes that are already expired. This is
			expected behavior: since TOTP codes are based on your local system clock, it's normal for your
			clock to be slightly off compared to the server (and it's also annoying to have an exactly
			30-second window to enter the code). Servers compensate by allowing a small window of codes to
			work, rather than just one code. There's not a requirement for the window size, but the RFC
			recommends using a window size of 1, which is what this site is configured to do.
		</p>

		<p>Let's look at this time window more visually:</p>

		<Portal label="visualization">
			<WindowVisualizer />
		</Portal>

		<p />

		<MailingListCta />

		<sup>1</sup> Footnote here.
	</article>
</main>
