<script lang="ts">
	export let mfaInitComplete = false;

	import QRCode from 'qrcode';
	import { counter, secret } from './store';
	import Button from '$lib/button.svelte';
	import ControlledInput from '$lib/input.svelte';
	import { DT, hmac } from './mfaUtils';
	import { onMount } from 'svelte';

	let errorMessage = '';
	let codeIsValid = false;

	let secretChunks = [$secret];
	let totpUri = '';
	let qrDataUrl = '';
	let inputCode = '';
	let darkQr = false;

	onMount(() => {
		darkQr =
			(window?.matchMedia && window?.matchMedia('(prefers-color-scheme: dark)').matches) ?? false;

		window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', (event) => {
			darkQr = event.matches;
		});
	});

	$: secretChunks = $secret.match(/.{2,8}/g) ?? [];
	$: {
		totpUri = `otpauth://totp/JacksonWelsh:user@example.com?secret=${$secret}&issuer=JacksonWelsh&algorithm=SHA1&digits=6&period=30`;
		QRCode.toDataURL(totpUri, {
			color: {
				light: '#ffffff00',
				dark: darkQr ? '#ffffffff' : '#000000ff'
			}
		}).then((url) => (qrDataUrl = url));
	}

	const copy = (e: MouseEvent, s: string) => {
		navigator.clipboard.writeText(s);
		const target = e.target as HTMLButtonElement;

		const oldText = target.innerText;
		target.innerText = 'Copied!';

		setTimeout(() => {
			target.innerText = oldText;
		}, 1500);
	};

	const validateCode = async () => {
		const validityRange = 1;
		const counterInt = parseInt($counter);

		for (let i = counterInt - validityRange; i <= counterInt + validityRange; ++i) {
			const code = DT((await hmac($secret, i.toString()))!);

			if (code.toString().padStart(6, '0') === inputCode.trim()) {
				errorMessage = '';
				codeIsValid = true;
				mfaInitComplete = true;
				return;
			}
		}

		errorMessage =
			"Invalid code, please check that your MFA device has the correct time and you've entered the secret correctly.";
		codeIsValid = false;
	};

	const reset = () => {
		inputCode = '';
		codeIsValid = false;
	};
</script>

<div class="p-4" id="seedInitRoot">
	<h2 class="text-2xl mt-0">Set up MFA for ZomboCom</h2>
	{#if !codeIsValid}
		{#if errorMessage !== ''}
			<div
				class="flex items-center rounded-md border dark:border-red-600 border-red-400 dark:bg-red-900/25 bg-red-100 dark:text-red-200 text-red-800 p-4 mb-4"
			>
				<div class="text-sm">{errorMessage}</div>
			</div>
		{/if}

		{#if qrDataUrl !== ''}
			<img src={qrDataUrl} alt={$secret} class="mx-auto" />
		{/if}
		<div class="flex gap-4 justify-center">
			{#each secretChunks as chunk}
				<span>{chunk}</span>
			{/each}
		</div>
		<div class="flex gap-4 justify-center my-4">
			<Button on:click={(e) => copy(e, $secret)}>Copy secret string</Button>
			<Button on:click={(e) => copy(e, totpUri)} variant="secondary">Copy TOTP URI</Button>
		</div>
		<form on:submit|preventDefault={validateCode}>
			<ControlledInput
				bind:value={inputCode}
				label="Enter the 6-digit code generated by your authenticator"
			/>
			<Button type="submit">submit</Button>
		</form>
	{:else}
		<div
			class="flex items-center rounded-md border dark:border-green-600 border-green-400 dark:bg-green-900/25 bg-green-100 dark:text-green-200 text-green-800 p-4 mb-4"
		>
			<div class="text-sm">
				That's a valid code! You've successfully initialized your MFA device.
			</div>
		</div>

		<Button on:click={reset}>Go back</Button>
	{/if}
</div>
